"""
Role C — Copilot & Retrieval Backend
Phase 1, Steps 1.2 & 1.3: Initialize Chroma vector database and seed live pipeline events.
"""

import os
import json
import chromadb
from dotenv import load_dotenv

load_dotenv()

PERSIST_DIR = os.getenv("CHROMA_PERSIST_DIR", "./chroma_db")
COLLECTION_NAME = os.getenv("CHROMA_COLLECTION_NAME", "pattern_of_life")
PIPELINE_JSON_PATH = os.getenv("PIPELINE_JSON_PATH", "../output/events_cam0.json")


def get_chroma_client():
    os.makedirs(PERSIST_DIR, exist_ok=True)
    client = chromadb.PersistentClient(path=PERSIST_DIR)
    print(f"[Chroma] Persistent client initialized at: {os.path.abspath(PERSIST_DIR)}")
    return client


def get_or_create_collection(client):
    collection = client.get_or_create_collection(
        name=COLLECTION_NAME,
        metadata={"description": "CCTV pattern-of-life tracking events for analyst copilot"},
    )
    print(f"[Chroma] Collection '{COLLECTION_NAME}' ready — current count: {collection.count()}")
    return collection


def load_real_pipeline_events(json_path=PIPELINE_JSON_PATH):
    """
    Loads real event records generated by the tracking pipeline and constructs
    clean semantic documents and structured metadata profiles.
    """
    if not os.path.exists(json_path):
        print(f"\n❌ ERROR: Could not find pipeline output at '{json_path}'")
        print("Please ensure Roles A & B have successfully executed 'build_events.py' first.\n")
        return []

    print(f"\n[Ingest] Reading live pipeline data from: {os.path.abspath(json_path)}")
    with open(json_path, "r") as f:
        try:
            pipeline_data = json.load(f)
        except json.JSONDecodeError as e:
            print(f"❌ ERROR: '{json_path}' contains malformed JSON data. Detail: {e}")
            return []

    formatted_events = []
    
    for i, event in enumerate(pipeline_data):
        # Generate structural IDs to track each entry distinctly
        event_id = f"evt_live_{event.get('camera_id', 'cam')}_{event.get('track_id', 0)}_{i}"
        
        # Build out a descriptive, natural-language document for hybrid vector matching
        # Handles cases where no objects are tracked safely
        carried_str = (
            f"carrying a {event['object_color']} {event['object_class']}"
            if event.get("object_class", "none") != "none"
            else "with no distinctive carried object detected"
        )
        
        document_text = (
            f"Person detected on {event.get('camera_id', 'unknown_cam')} (ref: {event.get('frame_ref', 'N/A')}), "
            f"tracked as ID {event.get('track_id', 'unknown')}, {carried_str} "
            f"with a tracking confidence of {event.get('confidence', 0.0)}."
        )

        # Build clean metadata filters matching the data types your filters rely on
        metadata_profile = {
            "camera_id": str(event.get("camera_id", "none")),
            "track_id": int(event.get("track_id", 0)),
            "frame_ref": str(event.get("frame_ref", "none")),
            "object_class": str(event.get("object_class", "none")),
            "object_color": str(event.get("object_color", "none")),
            "confidence": float(event.get("confidence", 0.0)),
        }

        formatted_events.append({
            "id": event_id,
            "document": document_text,
            "metadata": metadata_profile
        })

    return formatted_events


def upsert_events(collection, events):
    if not events:
        print("[Chroma] No events available to upsert.")
        return

    collection.upsert(
        ids=[e["id"] for e in events],
        documents=[e["document"] for e in events],
        metadatas=[e["metadata"] for e in events],
    )
    print(f"[Chroma] Upserted {len(events)} events into '{COLLECTION_NAME}' — total count: {collection.count()}")


def verify_seed_data(collection):
    print("\n" + "=" * 60)
    print("VERIFICATION QUERIES (LIVE DATA TEST)")
    print("=" * 60)

    # Test 1: High-level semantic evaluation
    print("\n[Test 1] Semantic search: 'backpack'")
    results = collection.query(query_texts=["backpack"], n_results=2)
    if results and results["documents"] and results["documents"][0]:
        for i, (doc, dist, meta) in enumerate(zip(results["documents"][0], results["distances"][0], results["metadatas"][0])):
            print(f"  {i+1}. [{dist:.4f}] {doc}")
            print(f"     metadata: camera={meta['camera_id']}, color={meta['object_color']}, class={meta['object_class']}")
    else:
        print("  -> No vector matches returned.")

    # Test 2: Standard tracking evaluation 
    print("\n[Test 2] Metadata check: camera_id = 'cam_0'")
    results = collection.get(where={"camera_id": "cam_0"}, limit=3)
    if results and results["documents"]:
        for doc, meta in zip(results["documents"], results["metadatas"]):
            print(f"  - {doc}")
            print(f"    frame_ref={meta['frame_ref']}, color={meta['object_color']}")
    else:
        print("  -> No entries found matching camera_id = 'cam_0'.")

    print("\n" + "=" * 60)
    print("Chroma index refresh complete. End-to-end integration unblocked.")
    print("=" * 60)


def main():
    print("\n" + "=" * 60)
    print("ROLE C: COPILOT & RETRIEVAL — PHASE 1: PIPELINE INGESTION")
    print("=" * 60 + "\n")
    
    client = get_chroma_client()
    collection = get_or_create_collection(client)
    
    # Read the data straight from the pipeline JSON instead of the old stub array
    events = load_real_pipeline_events()
    
    if events:
        print(f"[Seed] Successfully parsed {len(events)} live tracking records.")
        upsert_events(collection, events)
        verify_seed_data(collection)


if __name__ == "__main__":
    main()
